package com.mycompany.mapita.modelo;
// Generated 12/02/2019 02:37:32 PM by Hibernate Tools 4.3.1



/**
 * Marcador generated by hbm2java
 */
public class Marcador  implements java.io.Serializable {


     private int idmarcador;
     private String descripcion;
     private double longitud;
     private double latitud;
     private int usuarioid;

    public Marcador() {
    }

    public Marcador(int idmarcador, String descripcion, double longitud, double latitud, int usuarioid) {
       this.idmarcador = idmarcador;
       this.descripcion = descripcion;
       this.longitud = longitud;
       this.latitud = latitud;
       this.usuarioid = usuarioid;
    }
   
    public int getIdmarcador() {
        return this.idmarcador;
    }
    
    public void setIdmarcador(int idmarcador) {
        this.idmarcador = idmarcador;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public double getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(double longitud) {
        this.longitud = longitud;
    }
    public double getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(double latitud) {
        this.latitud = latitud;
    }
    public int getUsuarioid() {
        return this.usuarioid;
    }
    
    public void setUsuarioid(int usuarioid) {
        this.usuarioid = usuarioid;
    }




}


