package modelo;
// Generated 26/03/2019 03:59:19 PM by Hibernate Tools 4.3.1



/**
 * Comentarista generated by hbm2java
 */
public class Comentarista  implements java.io.Serializable {


     private int idcomentarista;
     private String nombre;
     private String correo;
     private String contrasenia;

    public Comentarista() {
    }

    public Comentarista(int idcomentarista, String nombre, String correo, String contrasenia) {
       this.idcomentarista = idcomentarista;
       this.nombre = nombre;
       this.correo = correo;
       this.contrasenia = contrasenia;
    }
   
    public int getIdcomentarista() {
        return this.idcomentarista;
    }
    
    public void setIdcomentarista(int idcomentarista) {
        this.idcomentarista = idcomentarista;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }




}


