package modelo;
// Generated 26/03/2019 03:59:19 PM by Hibernate Tools 4.3.1



/**
 * Comentario generated by hbm2java
 */
public class Comentario  implements java.io.Serializable {


     private int idcomentario;
     private String contenido;
     private double calificacion;
     private int comentarista;
     private int marcador;

    public Comentario() {
    }

    public Comentario(int idcomentario, String contenido, double calificacion, int comentarista, int marcador) {
       this.idcomentario = idcomentario;
       this.contenido = contenido;
       this.calificacion = calificacion;
       this.comentarista = comentarista;
       this.marcador = marcador;
    }
   
    public int getIdcomentario() {
        return this.idcomentario;
    }
    
    public void setIdcomentario(int idcomentario) {
        this.idcomentario = idcomentario;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }
    public double getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(double calificacion) {
        this.calificacion = calificacion;
    }
    public int getComentarista() {
        return this.comentarista;
    }
    
    public void setComentarista(int comentarista) {
        this.comentarista = comentarista;
    }
    public int getMarcador() {
        return this.marcador;
    }
    
    public void setMarcador(int marcador) {
        this.marcador = marcador;
    }




}


