package modelo;
// Generated 26/03/2019 03:59:19 PM by Hibernate Tools 4.3.1



/**
 * Informador generated by hbm2java
 */
public class Informador  implements java.io.Serializable {


     private String correo;
     private String nombre;
     private String contrasenia;

    public Informador() {
    }

    public Informador(String correo, String nombre, String contrasenia) {
       this.correo = correo;
       this.nombre = nombre;
       this.contrasenia = contrasenia;
    }
   
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }




}


