package modelo;
// Generated 26/03/2019 03:59:19 PM by Hibernate Tools 4.3.1



/**
 * Marcador generated by hbm2java
 */
public class Marcador  implements java.io.Serializable {


     private int idmarcador;
     private String descripcion;
     private String datosExtra;
     private double longitud;
     private double latitud;
     private int tema;

    public Marcador() {
    }

	
    public Marcador(int idmarcador, String descripcion, double longitud, double latitud, int tema) {
        this.idmarcador = idmarcador;
        this.descripcion = descripcion;
        this.longitud = longitud;
        this.latitud = latitud;
        this.tema = tema;
    }
    public Marcador(int idmarcador, String descripcion, String datosExtra, double longitud, double latitud, int tema) {
       this.idmarcador = idmarcador;
       this.descripcion = descripcion;
       this.datosExtra = datosExtra;
       this.longitud = longitud;
       this.latitud = latitud;
       this.tema = tema;
    }
   
    public int getIdmarcador() {
        return this.idmarcador;
    }
    
    public void setIdmarcador(int idmarcador) {
        this.idmarcador = idmarcador;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getDatosExtra() {
        return this.datosExtra;
    }
    
    public void setDatosExtra(String datosExtra) {
        this.datosExtra = datosExtra;
    }
    public double getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(double longitud) {
        this.longitud = longitud;
    }
    public double getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(double latitud) {
        this.latitud = latitud;
    }
    public int getTema() {
        return this.tema;
    }
    
    public void setTema(int tema) {
        this.tema = tema;
    }




}


