package modelo;
// Generated 26/03/2019 03:59:19 PM by Hibernate Tools 4.3.1



/**
 * Tema generated by hbm2java
 */
public class Tema  implements java.io.Serializable {


     private int idtema;
     private String nombre;
     private String informador;

    public Tema() {
    }

    public Tema(int idtema, String nombre, String informador) {
       this.idtema = idtema;
       this.nombre = nombre;
       this.informador = informador;
    }
   
    public int getIdtema() {
        return this.idtema;
    }
    
    public void setIdtema(int idtema) {
        this.idtema = idtema;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getInformador() {
        return this.informador;
    }
    
    public void setInformador(String informador) {
        this.informador = informador;
    }




}


